using System;
using System.Collections.Generic;
using System.Linq;
using Godot;

/// <summary>
/// 成就管理器 — 里程碑 + 挑战 + 彩蛋三类成就
/// </summary>
public partial class AchievementManager : Node
{
    private GameManager _gm;

    public List<Achievement> AllAchievements { get; private set; } = new();
    public HashSet<string> Unlocked { get; private set; } = new();
    public HashSet<string> NewUnlocks { get; private set; } = new(); // 本轮新解锁（用于弹窗）

    // ── 彩蛋成就追踪 ──
    private int _rejectedTaskCount;
    private bool _hasNameClash;
    private bool _hasFiredCEO;
    private int _idleMonths;

    private static readonly HashSet<string> _knownBigGames = new(StringComparer.OrdinalIgnoreCase)
    {
        "和平精英","Game for Peace",
        "金铲铲","金铲铲之战","Golden Shovel",
        "王者荣耀","Honor of Kings","Arena of Valor",
        "英雄联盟","League of Legends","LOL",
        "穿越火线","CrossFire","CF",
        "地下城与勇士","DNF","던전앤파이터",
        "天涯明月刀",
        "逆水寒","Justice",
        "斗战神",
        "QQ飞车","QQ Speed",
        "QQ炫舞","QQ Dance",
        "跑跑卡丁车","Crazyracing Kartrider",
        "使命召唤手游","Call of Duty Mobile","COD手游",
        "原神","Genshin Impact","Genshin",
        "崩坏3","崩坏","Honkai Impact 3rd",
        "崩坏星穹铁道","星穹铁道","Honkai Star Rail",
        "绝区零","Zenless Zone Zero",
        "崩坏学园2","崩坏学园",
        "梦幻西游","Fantasy Westward Journey",
        "大话西游",
        "阴阳师","Onmyoji",
        "第五人格","Identity V",
        "永劫无间","Naraka Bladepoint","Naraka",
        "明日方舟","Arknights",
        "碧蓝航线","Azur Lane",
        "天下3","天下",
        "倩女幽魂",
        "率土之滨",
        "荒野行动","Knives Out",
        "蛋仔派对","Eggy Party",
        "光遇","Sky","Sky Children of Light",
        "决战平安京",
        "魔兽世界","World of Warcraft","WoW",
        "魔兽争霸","Warcraft","Warcraft III",
        "星际争霸","StarCraft","StarCraft II",
        "暗黑破坏神","Diablo","Diablo II","Diablo III","Diablo IV",
        "守望先锋","Overwatch","Overwatch 2",
        "炉石传说","Hearthstone",
        "风暴英雄","Heroes of the Storm",
        "暗黑不朽","Diablo Immortal",
        "Dota","Dota 2",
        "反恐精英","Counter-Strike","CS","CSGO","Counter-Strike 2",
        "半衰期","Half-Life","Half-Life 2",
        "传送门","Portal","Portal 2",
        "求生之路","Left 4 Dead","Left 4 Dead 2",
        "军团要塞","Team Fortress","Team Fortress 2",
        "超级马里奥","Super Mario","Mario",
        "塞尔达传说","塞尔达","Zelda","The Legend of Zelda","Breath of the Wild","Tears of the Kingdom",
        "宝可梦","口袋妖怪","神奇宝贝","Pokémon","Pokemon","Pokemon GO",
        "动物森友会","Animal Crossing",
        "喷射战士","Splatoon",
        "马里奥赛车","Mario Kart",
        "任天堂明星大乱斗","Super Smash Bros",
        "星之卡比","Kirby",
        "银河战士","Metroid","Metroid Prime",
        "异度之刃","Xenoblade","Xenoblade Chronicles",
        "火焰之纹章","Fire Emblem",
        "大金刚","Donkey Kong",
        "皮克敏","Pikmin",
        "健身环大冒险","Ring Fit Adventure",
        "Nintendo Labo","Nintendo Switch",
        "异度神剑",
        "路易吉洋楼","Luigi Mansion",
        "纸片马里奥","Paper Mario",
        "斯普拉遁",
        "战神","God of War","God of War Ragnarok",
        "最后生还者","The Last of Us",
        "神秘海域","Uncharted",
        "地平线","Horizon Zero Dawn","Horizon Forbidden West",
        "对马岛之魂","Ghost of Tsushima",
        "蜘蛛侠","Spider-Man","Marvel's Spider-Man",
        "麻布仔","Sackboy",
        "瑞奇与叮当","Ratchet & Clank",
        "死亡搁浅","Death Stranding",
        "血源诅咒","Bloodborne",
        "恶魔之魂","Demon's Souls",
        "GT赛车","Gran Turismo","Gran Turismo 7",
        "直到黎明","Until Dawn",
        "底特律变人","Detroit","Detroit Become Human",
        "漫威金刚狼","Marvel's Wolverine",
        "战地","Battlefield","Battlefield V","Battlefield 2042","Battlefield 1",
        "FIFA","EA Sports FC",
        "极品飞车","Need for Speed",
        "模拟人生","The Sims",
        "星球大战","Star Wars Battlefront","Star Wars Jedi","Star Wars Outlaws",
        "APEX英雄","Apex Legends",
        "质量效应","Mass Effect",
        "龙腾世纪","Dragon Age",
        "泰坦陨落","Titanfall","Titanfall 2",
        "植物大战僵尸","Plants vs Zombies","PvZ",
        "死亡空间","Dead Space",
        "双人成行","It Takes Two",
        "逃出生天","A Way Out",
        "镜之边缘","Mirror Edge",
        "命令与征服","Command & Conquer","Red Alert",
        "刺客信条","Assassin's Creed",
        "孤岛惊魂","Far Cry",
        "看门狗","Watch Dogs","Watch Dogs 2","Watch Dogs Legion",
        "彩虹六号","Rainbow Six","Rainbow Six Siege",
        "全境封锁","The Division",
        "细胞分裂","Splinter Cell",
        "幽灵行动","Ghost Recon",
        "舞力全开","Just Dance",
        "纪元","Anno","Anno 1800",
        "英灵殿","Valhalla",
        "荣耀战魂","For Honor",
        "飙酷车神","The Crew",
        "光之子","Child of Light",
        "勇敢的心","Valiant Hearts",
        "渡神纪","Immortals Fenyx Rising",
        "光环","Halo",
        "战争机器","Gears of War","Gears 5",
        "极限竞速","Forza","Forza Horizon","Forza Motorsport",
        "我的世界","Minecraft",
        "帝国时代","Age of Empires","Age of Empires II","Age of Empires IV",
        "毁灭战士","Doom","Doom Eternal",
        "辐射","Fallout","Fallout 4","Fallout 76",
        "上古卷轴","The Elder Scrolls","Skyrim",
        "星空","Starfield",
        "盗贼之海","Sea of Thieves",
        "完美黑暗","Perfect Dark",
        "微软模拟飞行","Flight Simulator",
        "禁闭求生","Grounded",
        "Pentiment",
        "脑航员","Psychonauts","Psychonauts 2",
        "地狱之刃","Hellblade","Senua Sacrifice",
        "日落过载","Sunset Overdrive",
        "腐烂国度","State of Decay",
        "忍者理论","Ninja Theory",
        "生化危机","Resident Evil","Resident Evil 2","Resident Evil 4","Resident Evil Village",
        "鬼泣","Devil May Cry","Devil May Cry 5",
        "怪物猎人","Monster Hunter","Monster Hunter World","Monster Hunter Rise",
        "街头霸王","Street Fighter","Street Fighter 6",
        "洛克人","Mega Man",
        "逆转裁判","Phoenix Wright","Ace Attorney",
        "大逆裁判","Great Ace Attorney",
        "龙之信条","Dragon Dogma","Dragon Dogma 2",
        "黑暗之魂","Dark Souls","Dark Souls III",
        "艾尔登法环","Elden Ring",
        "只狼","Sekiro","Sekiro Shadows Die Twice",
        "铁拳","Tekken","Tekken 8",
        "皇牌空战","Ace Combat",
        "传说系列","Tales of","Tales of Arise",
        "噬血代码","Code Vein",
        "噬神者","God Eater",
        "偶像大师","Idolmaster",
        "太鼓达人","Taiko no Tatsujin",
        "最终幻想","Final Fantasy","FF7","FF14",
        "勇者斗恶龙","Dragon Quest","Dragon Quest XI",
        "王国之心","Kingdom Hearts",
        "古墓丽影","Tomb Raider","Rise of the Tomb Raider",
        "尼尔","NieR","NieR Automata",
        "八方旅人","Octopath Traveler",
        "杀出重围","Deus Ex",
        "奇异人生","Life is Strange",
        "侠盗猎车手","Grand Theft Auto","GTA","GTA V","GTA Online","GTA 5",
        "荒野大镖客","Red Dead Redemption","Red Dead Redemption 2","RDR2",
        "文明","Civilization","Sid Meier's Civilization","Civilization VI",
        "NBA 2K",
        "WWE 2K",
        "无主之地","Borderlands",
        "生化奇兵","BioShock",
        "幽浮","XCOM","XCOM 2",
        "漫威暗夜之子","Marvel Midnight Suns",
        "黑手党","Mafia",
        "巫师","The Witcher","Witcher 3",
        "赛博朋克2077","赛博朋克","Cyberpunk 2077",
        "泰拉瑞亚","Terraria",
        "星露谷物语","Stardew Valley",
        "空洞骑士","Hollow Knight",
        "死亡细胞","Dead Cells",
        "哈迪斯","Hades","Hades II",
        "传说之下","Undertale",
        "茶杯头","Cuphead",
        "蔚蓝","Celeste",
        "奥日","Ori","Ori and the Blind Forest","Ori Will of the Wisps",
        "以撒的结合","Binding of Isaac",
        "杀戮尖塔","Slay the Spire",
        "戴森球计划","Dyson Sphere Program",
        "鬼谷八荒",
        "修仙模拟器","Amazing Cultivation Simulator",
        "太吾绘卷",
        "暗黑地牢","Darkest Dungeon",
        "雨中冒险","Risk of Rain","Risk of Rain 2",
        "挺进地牢","Enter the Gungeon",
        "吸血鬼幸存者","Vampire Survivors",
        "潜水员戴夫","Dave the Diver",
        "咩咩启示录","Cult of the Lamb",
        "星界边境","Starbound",
        "环世界","RimWorld",
        "幻兽帕鲁","Palworld",
        "致命公司","Lethal Company",
        "严阵以待","Ready or Not",
        "深岩银河","Deep Rock Galactic",
        "收获日","Payday","Payday 2","Payday 3",
        "逃离塔科夫","Escape from Tarkov",
        "七日杀","7 Days to Die",
        "僵尸毁灭工程","Project Zomboid",
        "博德之门","Baldur's Gate","Baldur's Gate 3",
        "神界原罪","Divinity Original Sin","Divinity Original Sin 2",
        "极乐迪斯科","Disco Elysium",
        "永恒之柱","Pillars of Eternity",
        "开拓者","Pathfinder","Pathfinder Wrath of the Righteous",
        "天外世界","The Outer Worlds",
        "辐射新维加斯","Fallout New Vegas",
        "蔑视","Scorn",
        "控制","Control",
        "心灵杀手","Alan Wake","Alan Wake 2",
        "地铁","Metro","Metro Exodus","Metro 2033",
        "消逝的光芒","Dying Light","Dying Light 2",
        "森林","The Forest","Sons of the Forest",
        "绿色地狱","Green Hell",
        "英灵神殿","Valheim",
        "夜族崛起","V Rising",
        "腐蚀","Rust",
        "方舟","ARK","ARK Survival Evolved","Ark Survival Ascended",
        "流放之路","Path of Exile",
        "星际战甲","Warframe",
        "命运2","Destiny 2",
        "战争雷霆","War Thunder",
        "坦克世界","World of Tanks","WoT",
        "战舰世界","World of Warships","WoWs",
        "全面战争","Total War","Total War Warhammer",
        "英雄无敌","Heroes of Might and Magic",
        "魔法门","Might and Magic",
        "仙剑奇侠传","仙剑",
        "古剑奇谭",
        "剑侠情缘",
        "天龙八部",
        "热血传奇","传奇",
        "征途",
        "问道",
        "完美世界",
        "剑灵","Blade & Soul",
        "龙之谷","Dragon Nest",
        "斗罗大陆",
        "斗破苍穹",
        "一念逍遥",
        "最强蜗牛",
        "江南百景图",
        "开心消消乐",
        "恋与制作人",
        "闪耀暖暖","奇迹暖暖",
        "元气骑士",
        "迷你世界",
        "香肠派对",
        "三国杀",
        "狼人杀",
        "女神异闻录","Persona","Persona 5","Persona 3","Persona 4",
        "合金装备","Metal Gear Solid","MGS",
        "如龙","Yakuza","Like a Dragon",
        "蔚蓝档案","Blue Archive",
        "少女前线","Girls' Frontline",
        "幻塔","Tower of Fantasy",
        "鸣潮","Wuthering Waves",
        "重返未来1999","Reverse 1999",
        "剑星","Stellar Blade",
        "赛马娘","Uma Musume",
        "公主连结","Princess Connect","Princess Connect ReDive",
        "FGO","Fate Grand Order",
        "碧蓝幻想","Granblue Fantasy",
        "世界弹射物语",
        "怪物弹珠",
        "智龙迷城","Puzzle & Dragons",
        "神魔之塔","Tower of Saviors",
        "白猫Project",
        "糖果粉碎传奇","Candy Crush",
        "愤怒的小鸟","Angry Birds",
        "部落冲突","Clash of Clans","COC",
        "皇室战争","Clash Royale",
        "海岛奇兵","Boom Beach",
        "卡通农场","Hay Day",
        "水果忍者","Fruit Ninja",
        "神庙逃亡","Temple Run",
        "地铁跑酷","Subway Surfers",
        "合成大西瓜",
        "羊了个羊",
        "旅行青蛙",
        "未定事件簿",
        "光与夜之恋",
        "食物语",
        "天地劫",
        "梦幻模拟战","Langrisser",
        "万国觉醒","Rise of Kingdoms",
        "王国纪元","Lords Mobile",
        "剑与远征","AFK Arena",
        "King of Fighters","拳皇","KOF",
        "侍魂","Samurai Shodown",
        "真人快打","Mortal Kombat",
        "不义联盟","Injustice",
        "罪恶装备","Guilty Gear",
        "苍翼默示录","BlazBlue",
        "死或生","Dead or Alive",
        "灵魂能力","Soulcalibur",
        "Jump Force",
        "龙珠","Dragon Ball","Dragon Ball FighterZ","七龙珠",
        "火影忍者","Naruto","Naruto Shippuden",
        "海贼王","One Piece",
        "鬼灭之刃","Demon Slayer","Kimetsu no Yaiba",
        "死神","Bleach",
        "进击的巨人","Attack on Titan",
        "英雄传说","轨迹","Trails","Kiseki",
        "伊苏","Ys",
        "炼金工房","Atelier",
        "工作室系列",
        "魔界战记","Disgaea",
        "十三机兵防卫圈","13 Sentinels",
        "奥丁领域","Odin Sphere",
        "龙之皇冠","Dragon Crown",
        "圣兽之王","Unicorn Overlord",
        "真女神转生","Shin Megami Tensei",
        "世界树迷宫","Etrian Odyssey",
        "啪嗒砰","Patapon",
        "乐克乐克","LocoRoco",
        "重力异想世界","Gravity Rush",
        "东京幻都","Tokyo Xanadu",
        "符文工房","Rune Factory",
        "牧场物语","Story of Seasons","Harvest Moon",
        "极限脱出","Zero Escape",
        "弹丸论破","Danganronpa",
        " Fate","Fate Stay Night",
        "崩坏星穹铁道","Silver Wolf",
        "僵尸围城","Dead Rising",
        "出击飞龙","Strider",
        "大航海时代","Uncharted Waters",
        "太阁立志传",
        "信长的野望","Nobunaga Ambition",
        "三国志","Romance of the Three Kingdoms",
        "仁王","Nioh","Nioh 2",
        "卧龙","Wo Long",
        "浪人崛起","Rise of the Ronin",
        "忍者龙剑传","Ninja Gaiden",
        "猎天使魔女","Bayonetta",
        "征服","Vanquish",
        "绝对征服",
        "Virtua Fighter","VR战士",
        "如龙","Yakuza","Like a Dragon","Judgment","审判之眼","审判之逝",
        "超侦探事件簿","Master Detective Archives",
        "幽灵线东京","Ghostwire Tokyo",
        "Hi-Fi Rush",
        "完美音浪",
        "日落黄昏时","As Dusk Falls",
        "隐迹渐现","Pentiment",
        "帝国时代","Age of Mythology",
        "神话时代",
        "国家的崛起","Rise of Nations",
        "要塞","Stronghold",
        "纪元变异","ANNO Mutationem",
        "侠客风云传",
        "河洛群侠传",
        "武林群侠传",
        "金庸群侠传",
        "天命奇御",
        "活侠传",
        "大侠立志传",
        "逸剑风云决",
        "暖雪","Warm Snow",
        "嗜血印","Bloody Spell",
        "失落城堡","Lost Castle",
        "霓虹深渊","Neon Abyss",
        "归家异途",
        "部落与弯刀",
        "汉家江湖",
        "月圆之夜",
        "贪婪洞窟",
        "不思议迷宫",
        "恶果之地",
        "比特小队",
        "幸存者危城",
        "迷雾侦探",
        "山海旅人",
        "烟火",
        "三伏",
        "纸嫁衣",
        "港诡实录",
        "你好邻居","Hello Neighbor",
        "小小梦魇","Little Nightmares",
        "玩具熊的五夜后宫","Five Nights at Freddy","FNAF",
        "Poppy Playtime",
        "章鱼爹",
        "Bendy and the Ink Machine",
        "黑暗欺骗","Dark Deception",
        "修道院","Amnesia",
        "失忆症",
        "SOMA",
        "Outlast","逃生",
        "采石场惊魂","The Quarry",
        "黑相集","Dark Pictures Anthology",
        "棉兰号","Man of Medan",
        "稀望镇","Little Hope",
        "灰冥界","House of Ashes",
        "我心中的恶魔","Devil in Me",
        "暴雨","Heavy Rain",
        "超凡双生","Beyond Two Souls",
        "暴雨杀机",
        "行尸走肉","The Walking Dead","Telltale",
        "与狼同行","The Wolf Among Us",
        "无主之地传说","Tales from the Borderlands",
        "蝙蝠侠","Batman","Batman Arkham",
        "指环王","Lord of the Rings","中土世界","Middle-earth","Shadow of Mordor","Shadow of War",
        "疯狂麦克斯","Mad Max",
        "霍格沃茨之遗","Hogwarts Legacy",
        "赛博朋克","Cyberpunk",
        "电驭叛客",
        "吸血鬼","Vampyr",
        "瘟疫传说","A Plague Tale",
        "索尼克","Sonic","Sonic Frontiers",
        "愤怒的小鸟","Angry Bird",
        "割绳子","Cut the Rope",
        "鳄鱼小顽皮爱洗澡","Where My Water",
        "会说话的汤姆猫","Talking Tom",
        "我的世界","Minecraft",
        "Minecraft Dungeons",
        "Minecraft Legends",
        "Roblox","罗布乐思",
        "堡垒之夜","Fortnite",
        "糖豆人","Fall Guys",
        "在我们之中","Among Us",
        "鹅作剧","Untitled Goose Game",
        "Stray","流浪猫",
        "迷失",
        "Moss",
        "Astro Bot","宇宙机器人",
        "Astro Playroom",
        "Returnal","死亡回归",
        "恶魔城","Castlevania",
        "魂斗罗","Contra",
        "合金弹头","Metal Slug",
        "赤痕","Bloodstained",
        "忍者神龟","Teenage Mutant Ninja Turtles","TMNT",
        "双截龙","Double Dragon",
        "怒之铁拳","Streets of Rage",
        "Shovel Knight","铲子骑士",
        "墨西哥英雄","Guacamelee",
        "勇敢的哈克",
        "暗影火炬城","F.I.S.T.",
        "动物井","Animal Well",
        "Brotato","土豆兄弟",
        "Boneraiser Minions",
        "黎明前20分钟","20 Minutes Till Dawn",
        "Holocure",
        "Magic Survival",
        "灵魂石幸存者","Soulstone Survivors",
        "求生岛","Survival Island",
        "木筏求生","Raft",
        "深海迷航","Subnautica","Subnautica Below Zero",
        "美丽水世界",
        "帝国霸业","Empyrion",
        "太空工程师","Space Engineers",
        "异星工厂","Factorio",
        "幸福工厂","Satisfactory",
        "Captain of Industry",
        "Mindustry",
        "形状z","Shapez",
        "Planet Coaster","过山车之星",
        "Planet Zoo","动物园之星",
        "侏罗纪世界进化","Jurassic World Evolution",
        "双点医院","Two Point Hospital",
        "双点校园","Two Point Campus",
        "监狱建筑师","Prison Architect",
        "邪恶天才","Evil Genius",
        "地下城守护者","Dungeon Keeper",
        "主题医院","Theme Hospital",
        "过山车大亨","Rollercoaster Tycoon",
        "动物园大亨","Zoo Tycoon",
        "异种航员","Xenonauts",
        "铁血联盟","Jagged Alliance",
        "战争之人","Men of War",
        "英雄连","Company of Heroes",
        "战锤","Warhammer","Warhammer 40000",
        "战争黎明","Dawn of War",
        "鼠疫","Vermintide",
        "暗潮","Darktide",
        "星际战士","Space Marine",
        "全面战争战锤","Total War Warhammer",
        "欧洲卡车模拟","Euro Truck Simulator",
        "美国卡车模拟","American Truck Simulator",
        "模拟农场","Farming Simulator",
        "房产达人","House Flipper",
        "装机模拟器","PC Building Simulator",
        "洗车模拟","PowerWash Simulator",
        "汽车修理工模拟","Car Mechanic Simulator",
        "外科模拟","Surgeon Simulator",
        "我是面包","I Am Bread",
        "模拟山羊","Goat Simulator",
        "人类一败涂地","Human Fall Flat",
        "基佬大乱斗","Gang Beasts",
        "派对动物","Party Animals",
        "揍击派对","Pummel Party",
        "胡闹厨房","Overcooked","Overcooked 2",
        "双人成行","It Takes Two",
        "毛线小精灵","Unravel",
        "三位一体","Trine",
        "雷曼","Rayman",
        "古惑狼","Crash Bandicoot",
        "小龙斯派罗","Spyro",
        "麻布仔大冒险","Sackboy",
        "小小大星球","LittleBigPlanet",
        "胖公主","Fat Princess",
        "绝对英雄改造计划",
        "魔界战记","Disgaea",
        "召唤之夜","Summon Night",
        "光明系列","Shining",
        "梦幻之星","Phantasy Star","Phantasy Star Online",
        "封锁","Blue Protocol",
        "失落方舟","Lost Ark",
        "罗技","Lineage",
        "天堂","Lineage",
        "永恒之塔","Aion",
        "第九大陆","C9",
        "剑灵","Blade Soul",
        "TERA",
        "黑色沙漠","Black Desert Online",
        "上古世纪","ArcheAge",
        "EVE Online",
        "星战前夜",
        "无尽的拉格朗日",
        "无尽的未知",
        "HIT我打","HIT",
        "V4",
        "天堂2","Lineage II",
        "卓越之剑","Granado Espada",
        "仙境传说","Ragnarok Online","RO",
        "魔力宝贝","CrossGate",
        "石器时代","Stone Age",
        "冒险岛","MapleStory",
        "彩虹岛","LaTale",
        "泡泡堂","BNB","Crazy Arcade",
        "劲舞团","Audition",
        "劲乐团","O2Jam",
        "超级跑跑","TalesRunner",
        "街头篮球","FreeStyle",
        "热血江湖",
        "武林外传",
        "诛仙",
        "神魔大陆",
        "星辰变",
        "九阴真经",
        "笑傲江湖",
        "梦幻诛仙",
        "鹿鼎记",
        "大唐无双",
        "武魂",
        "镇魔曲",
        "乱斗西游",
        "英雄杀",
        "关云长",
        "真三国无双","Dynasty Warriors","真三",
        "战国无双","Samurai Warriors",
        "三国无双",
        "无双大蛇","Warriors Orochi",
        "仁王","Nioh",
        "卧龙","Wo Long Fallen Dynasty",
        "忍者龙剑传","Ninja Gaiden",
        "零","Fatal Frame",
        "死或生","Dead or Alive",
        "忍者外传","Ninja Gaiden",
        "炼金术士","Atelier",
        "工作室","Atelier",
        "蓝色反射","Blue Reflection",
        "苏菲的炼金工房","Atelier Sophie",
        "莱莎的炼金工房","Atelier Ryza",
        "边境保卫战","Border Defense",
        "原界之罪",
        "光明记忆","Bright Memory",
        "无限",
        "失落之魂","Lost Soul Aside",
        "黑神话悟空","Black Myth Wukong",
        "明末",
        "影之刃","Phantom Blade",
        "百面千相",
        "燕云十六声",
        "无限暖暖","Infinity Nikki",
        "Project MU",
        "阿瑞斯",
        "时空猎人",
        "时空召唤",
        "小米超神",
        "小米枪战",
        "终结者2",
        "全军出击",
        "刺激战场",
        "PUBG Mobile",
        "Free Fire",
        "荒野乱斗","Brawl Stars",
        "Brawl Stars",
        "炸弹人","Bomberman",
        "俄罗斯方块","Tetris",
        "吃豆人","Pac-Man",
        "太空侵略者","Space Invaders",
        "大蜜蜂","Galaga",
        "小蜜蜂",
        "坦克大战",
        "冒险岛","MapleStory",
        "DNF","던파",
        "永恒之塔","AION",
        "卓越之剑",
        "洛奇","Mabinogi",
        "洛奇英雄传","Vindictus",
        "TERA",
        "Cabal","决战",
        "Sword of the New World",
        "梦幻龙族",
        "艾尔之光","Elsword",
        "封印者","Closers",
        "Trinity",
        "超能战联",
        "暴能特区",
        "核心格斗",
        "超时空要爱",
        "失落的神庙",
        "古域",
        "降龙之剑",
        "天堂梦",
        "守护之剑",
        "猎魂",
        "巫师之怒",
        "地城之光",
        "颓废之心",
        "不败传说",
        "新世纪福音战士","EVA","Evangelion",
        "进击的巨人",
        "东京喰种","Tokyo Ghoul",
        "刀剑神域","Sword Art Online","SAO",
        "加速世界","Accel World",
        "魔法禁书目录","Index","Toaru",
        "某科学的超电磁炮","Railgun",
        "Re从零开始的异世界生活","Re Zero",
        "为美好的世界献上祝福","KonoSuba",
        "OVERLORD",
        "转生史莱姆","That Time I Got Reincarnated as a Slime",
        "咒术回战","Jujutsu Kaisen",
        "我的英雄学院","My Hero Academia",
        "一拳超人","One Punch Man",
        "电锯人","Chainsaw Man",
        "间谍过家家","Spy Family",
        "孤独摇滚","Bocchi the Rock",
        "摇曳露营","Laid-Back Camp",
        "冰菓","Hyouka",
        "凉宫春日","Haruhi Suzumiya",
        "CLANNAD",
        "Air",
        "Kanon",
        "Little Busters",
        "Rewrite",
        "Angel Beats",
        "Charlotte",
        "Key社",
        "秋之回忆","Memories Off",
        "告别回忆",
        "Ever17",
        "Never7",
        "Remember11",
        "12Riven",
        "无限轮回","Infinity",
        "命运石之门","Steins Gate","Steins Gate 0",
        "混沌之脑","Chaos Head",
        "混沌之子","Chaos Child",
        "机器人笔记","Robotics Notes",
        "匿名代码","Anonymous Code",
        "科学ADV",
        "海猫鸣泣之时","Umineko When They Cry",
        "寒蝉鸣泣之时","Higurashi When They Cry",
        "彼岸花盛开之夜",
        "恐怖惊魂夜","Kamaitachi No Yoru",
        "街",
        "428被封锁的涩谷","428 Shibuya Scramble",
        "逆转裁判","Ace Attorney","Phoenix Wright",
        "大逆转裁判","The Great Ace Attorney",
        "雷顿教授","Professor Layton",
        "雷顿神秘之旅",
        "雷顿vs逆转",
        "幽灵诡计","Ghost Trick",
        "弹丸论破","Danganronpa","弹丸论破希望学园与绝望高中生",
        "超级弹丸论破2","Danganronpa 2",
        "弹丸论破V3","Danganronpa V3",
        "绝对绝望少女",
        "极限脱出","Zero Escape",
        "999",
        "善人死亡","Virtue Last Reward",
        "零时困境","Zero Time Dilemma",
        "AI梦境档案","AI The Somnium Files",
        "AI梦境档案涅槃肇始",
        "世界末日俱乐部","World End Club",
        "黄昏三部曲",
        "炼金工房","Atelier",
        "玛丽的工作室","Atelier Marie",
        "艾莉的工作室","Atelier Elie",
        "莉莉的工作室","Atelier Lilie",
        "优蒂的工作室","Atelier Judie",
        "薇欧蕾特的工作室","Atelier Viorate",
        "伊莉斯的工作室","Atelier Iris",
        "玛娜学园","Mana Khemia",
        "萝洛娜的工作室","Atelier Rorona",
        "托托莉的工作室","Atelier Totori",
        "梅露露的工作室","Atelier Meruru",
        "爱夏的工作室","Atelier Ayesha",
        "爱丝卡与罗吉的工作室","Atelier Escha Logy",
        "夏莉的工作室","Atelier Shallie",
        "苏菲的工作室","Atelier Sophie",
        "菲利斯的工作室","Atelier Firis",
        "莉迪与苏瑞的工作室","Atelier Lydie Suelle",
        "露露亚的工作室","Atelier Lulua",
        "莱莎的工作室","Atelier Ryza",
        "秘密系列",
        "碧蓝幻想","Granblue Fantasy",
        "碧蓝幻想Versus","Granblue Fantasy Versus",
        "碧蓝幻想Relink","Granblue Fantasy Relink",
        "碧蓝幻想RPG",
        "失落的龙约","Dragalia Lost",
        "弹射世界","World Flipper",
        "世界弹射物语",
        "公主连结ReDive","Princess Connect ReDive",
        "公主连结",
        "超异域公主连结",
        "赛马娘Pretty Derby","Uma Musume",
        "偶像大师","Idolmaster",
        "偶像大师灰姑娘女孩","Idolmaster Cinderella Girls",
        "偶像大师百万现场","Idolmaster Million Live",
        "偶像大师闪耀色彩","Idolmaster Shiny Colors",
        "偶像大师SideM",
        "偶像大师星耀季节",
        "偶像大师星光舞台",
        "偶像大师全力以赴",
        "偶像大师2",
        "偶像大师SP",
        "偶像大师Dearly Stars",
        "Love Live!","Love Live School Idol Festival",
        "Love Live学园偶像祭",
        "Love Live学园偶像季群星闪耀",
        "Love Live虹咲学园",
        "Love Live Superstar",
        "Love Live莲之空",
        "少女歌剧","Revue Starlight",
        "BanG Dream","BanG Dream少女乐团派对",
        "D4DJ",
        "D4DJ Groovy Mix",
        "DJMax Respect",
        "DJMax Technika",
        "DJMax Portable",
        "DJMax Trilogy",
        "DJMax Fever",
        "EZ2DJ",
        "EZ2ON",
        "R2Beat",
        "Osu",
        "osu",
        "Muse Dash",
        "喵斯快跑",
        "Phigros",
        "Arcaea",
        "韵律源点",
        "Cytus",
        "Cytus II",
        "Deemo",
        "古树旋律",
        "VOEZ",
        "兰空",
        "Lanota",
        "Orzmic",
        "Dynamix",
        "Chain Bee",
        "同步音律",
        "同步音律喵赛克",
        "太鼓达人","Taiko no Tatsujin",
        "太鼓之达人",
        "咚锵",
        "啪嗒砰","Patapon",
        "啪嗒砰2",
        "啪嗒砰3",
        "乐克乐克","LocoRoco",
        "乐克乐克2",
        "我的暑假","Boku no Natsuyasumi",
        "蜡笔小新","Shin Chan",
        "蜡笔小新煤炭镇的小白",
        "蜡笔小新呼风唤雨",
        "哆啦A梦","Doraemon",
        "哆啦A梦牧场物语",
        "哆啦A梦大雄的月球探险",
        "哆啦A梦大雄的恐龙",
        "名侦探柯南","Detective Conan",
        "柯南",
        "金田一","Kindaichi",
        "金田一少年事件簿",
        "JOJO的奇妙冒险","JoJo Bizarre Adventure",
        "JOJO全明星大乱斗","JoJo All Star Battle",
        "JOJO天国之眼","JoJo Eyes of Heaven",
        "Fate","Fate Stay Night",
        "Fate Hollow Ataraxia",
        "Fate Unlimited Codes",
        "Fate Extella",
        "Fate Extella Link",
        "Fate Samurai Remnant",
        "Fate Grand Order","FGO",
        "魔法使之夜","Witch on the Holy Night",
        "月姬","Tsukihime",
        "月姬格斗","Melty Blood",
        "月姫",
        "空之境界","Kara no Kyoukai",
        "笑颜",
        "寒蝉",
        "海猫",
        "白色相簿","White Album",
        "白色相簿2",
        "White Album 2",
        "青空下的约定",
        "交响乐之雨",
        "雨",
        "水仙",
        "Narcissu",
        "120日元",
        "星之梦","Planetarian",
        "星之人",
        "悠久之翼","ef a fairy tale",
        "末日孤雄",
        "勇者",
        "狼与香辛料","Spice and Wolf",
        "狼与香辛料VR",
        "NO GAME NO LIFE","游戏人生",
        "游戏人生Zero",
        "从零开始的异世界生活","Re Zero",
        "Re从零开始的异世界生活",
        "为美好的世界献上祝福","KonoSuba",
        "素晴",
        "OVERLORD",
        "转生史莱姆","That Time I Got Reincarnated as a Slime",
        "关于我转生变成史莱姆这档事",
        "盾之勇者成名录","Rising of the Shield Hero",
        "盾勇",
        "无职转生","Mushoku Tensei",
        "葬送的芙莉莲","Frieren",
        "芙莉莲",
        "迷宫饭","Dungeon Meshi",
        "异世界舅舅",
        "异世界叔叔",
        "异世界失格",
        "异世界悠闲农家",
        "异世界魔王",
        "魔法科高中的劣等生","Mahouka",
        "魔劣",
        "魔法禁书目录","Index",
        "某科学的超电磁炮","Railgun",
        "某科学的一方通行",
        "某科学未元物质",
        "魔法禁书目录手游",
        "刀剑神域","Sword Art Online","SAO",
        "刀剑神域虚空幻界",
        "刀剑神域夺命凶弹",
        "刀剑神域彼岸游境",
        "刀剑神域彼岸",
        "刀剑神域记忆重组",
        "刀剑神域 Alicization",
        "加速世界","Accel World",
        "境界线上的地平线",
        "黑子的篮球","Kuroko Basketball",
        "灌篮高手","Slam Dunk",
        "灌篮高手手游",
        "足球小将","Captain Tsubasa",
        "足球小将翼",
        "天使之翼",
        "排球少年","Haikyuu",
        "排球少年手游",
        "网球王子","Prince of Tennis",
        "新网球王子",
        "网球王子手游",
        "棒球英豪","Touch",
        "王牌投手",
        "钻石王牌","Ace of Diamond",
        "钻A",
        "实况力量棒球","Power Pros",
        "实况棒球",
        "J联盟足球",
        "胜利十一人","Winning Eleven",
        "世界足球竞赛",
        "实况足球","Pro Evolution Soccer","PES",
        "eFootball",
        "FIFA",
        "EA Sports FC",
        "NBA 2K",
        "NBA Live",
        "NBA Jam",
        "NBA街头篮球",
        "NBA Ballers",
        "Madden NFL",
        "Madden橄榄球",
        "NHL",
        "NHL冰球",
        "MLB The Show",
        "MLB",
        "PGA Tour",
        "PGA巡回赛",
        "Tiger Woods PGA Tour",
        "The Masters",
        "WWE 2K",
        "WWE摔角",
        "WWE SmackDown",
        "WWE Raw",
        "WWE WrestleMania",
        "AEW Fight Forever",
        "Fire Pro Wrestling",
        "火爆摔角",
        "搏击之夜","Fight Night",
        "UFC",
        "Undisputed",
        "EA Sports UFC",
        "拳击俱乐部",
        "角斗士",
        "世嘉暴力",
        "世嘉街机",
        "VR战士",
        "Virtua Fighter",
        "VF",
        "VF2",
        "VF3",
        "VF4",
        "VF5",
        "铁拳","Tekken",
        "铁拳2",
        "铁拳3",
        "铁拳5",
        "铁拳6",
        "铁拳7",
        "铁拳8",
        "街头霸王","Street Fighter",
        "街霸2","Street Fighter II",
        "街霸Zero","Street Fighter Alpha",
        "街霸3","Street Fighter III",
        "街霸4","Street Fighter IV",
        "街霸5","Street Fighter V",
        "街霸6","Street Fighter 6",
        "街头霸王EX",
        "VS系列",
        "Marvel vs Capcom",
        "Marvel vs Capcom 2",
        "Marvel vs Capcom 3",
        "漫威大战卡普空",
        "SNK vs Capcom",
        "Capcom vs SNK",
        "卡普空对战SNK",
        "Tatsunoko vs Capcom",
        "龙之子VS卡普空",
        "Nintendo vs Capcom",
        "Project X Zone",
        "交叉领域计划",
        "无限",
        "终极漫威对卡普空",
        "MvC Infinite",
        "骷髅女孩","Skullgirls",
        "夜下降生","Under Night In-Birth",
        "夜下",
        "UNI",
        "电击文库零境交错",
        "电击文库FC",
        "电击文库格斗巅峰",
        "电击文库",
        "海贼王","One Piece",
        "海贼无双","One Piece Pirate Warriors",
        "海贼王燃烧热血",
        "海贼王寻秘世界",
        "海贼王时光旅诗",
        "海贼王奥德赛",
        "海贼王伟大航路",
        "海贼王Bounty Rush",
        "海贼王Treasure Cruise",
        "火影忍者","Naruto",
        "火影忍者疾风传",
        "火影忍者究极忍者风暴","Naruto Ultimate Ninja Storm",
        "火影忍者究极风暴4",
        "火影忍者究极风暴羁绊",
        "火影忍者手游",
        "火影忍者ol",
        "博人传","Boruto",
        "龙珠","Dragon Ball",
        "七龙珠",
        "龙珠Z",
        "龙珠超","Dragon Ball Super",
        "龙珠GT",
        "龙珠大冒险",
        "龙珠斗士Z","Dragon Ball FighterZ",
        "龙珠超宇宙","Dragon Ball Xenoverse",
        "龙珠超宇宙2",
        "龙珠Z卡卡罗特","Dragon Ball Kakarot",
        "龙珠英雄",
        "龙珠激战传说",
        "龙珠爆裂激战",
        "龙珠改",
        "龙珠天下一",
        "龙珠武道会",
        "龙珠电光火石",
        "龙珠Z武道会",
        "龙珠Sparking",
        "鬼灭之刃","Demon Slayer","Kimetsu no Yaiba",
        "鬼灭之刃火之神血风谭",
        "鬼灭之刃火之神",
        "鬼灭之刃血风谭",
        "鬼灭之刃日轮花",
        "鬼灭之刃游戏",
        "死神","Bleach",
        "死神Bleach",
        "灵魂升温",
        "死神嘉年华",
        "死神3",
        "死神FIGHT",
        "死神Brave Souls",
        "死神死神",
        "千年血战",
        "咒术回战","Jujutsu Kaisen",
        "咒术回战咒术大战",
        "咒术回战双华乱舞",
        "我的英雄学院","My Hero Academia",
        "我的英雄学院唯我正义",
        "我的英雄学院英雄体育祭",
        "我的英雄学院最强英雄",
        "一拳超人","One Punch Man",
        "一拳超人无名英雄",
        "一拳超人最强之男",
        "一拳超人正义执行",
        "电锯人","Chainsaw Man",
        "电锯人游戏",
        "间谍过家家","Spy x Family",
        "间谍过家家游戏",
        "间谍家家酒",
        "进击的巨人","Attack on Titan",
        "进击的巨人游戏",
        "进击的巨人人类最后之翼",
        "进击的巨人2",
        "进击的巨人Final Battle",
        "东京喰种","Tokyo Ghoul",
        "东京喰种游戏",
        "东京喰种Carnival",
        "东京喰种re",
        "东京复仇者","Tokyo Revengers",
        "重生之道",
        "亚人",
        "亚人游戏",
        "浪客剑心","Rurouni Kenshin",
        "浪客剑心游戏",
        "猎人","Hunter x Hunter",
        "全职猎人",
        "猎人游戏",
        "猎人×猎人",
        "HXH",
        "乱马1/2","Ranma 1/2",
        "犬夜叉","Inuyasha",
        "犬夜叉游戏",
        "犬夜叉奈落之战",
        "犬夜叉觉醒",
        "幽游白书","Yu Yu Hakusho",
        "幽游白书魔强统一战",
        "幽游白书游戏",
        "幽白",
        "LEVEL E",
        "恶魔奶爸",
        "魔人侦探食脑奈罗",
        "暗杀教室","Assassination Classroom",
        "杀老师",
        "章鱼老师",
        "学园孤岛",
        "学院孤岛",
        "学园默示录","Highschool of the Dead",
        "僵尸学园",
        "妖精的尾巴","Fairy Tail",
        "妖尾",
        "妖尾游戏",
        "妖精尾巴RPG",
        "七大罪","Seven Deadly Sins",
        "七原罪",
        "七大罪游戏",
        "七大罪光与暗之交战",
        "驱魔少年","D Gray Man",
        "D格雷少年",
        "黑执事","Black Butler",
        "黑执事游戏",
        "伯爵与妖精",
        "薄樱鬼","Hakuoki",
        "薄樱鬼游戏",
        "薄樱鬼真改",
        "绯色的碎片",
        "遥远时空中",
        "遥时",
        "金色琴弦",
        "安琪莉可",
        "Angelic",
        "新安琪莉可",
        "Neo Romance",
        "暗荣",
        "KOEI",
        "光荣特库摩",
        "光荣",
        "Game Republic",
        "日本一",
        "日本一软件",
        "Nippon Ichi",
        "角川",
        "Kadokawa",
        "fami通",
        "电击",
        "世嘉","Sega",
        "世嘉MD",
        "世嘉土星","Sega Saturn",
        "世嘉DC","Dreamcast",
        "世嘉Master System",
        "世嘉GG","Game Gear",
        "Mega Drive",
        "世嘉五代",
        "索尼克","Sonic",
        "索尼克边境","Sonic Frontiers",
        "索尼克狂热","Sonic Mania",
        "索尼克力量","Sonic Forces",
        "索尼克世代","Sonic Generations",
        "索尼克色彩","Sonic Colors",
        "索尼克释放","Sonic Unleashed",
        "索尼克竞速",
        "索尼克赛车","Sonic Racing",
        "索尼克大冒险","Sonic Adventure",
        "索尼克大冒险DX",
        "索尼克大冒险2",
        "索尼克英雄","Sonic Heroes",
        "索尼克暗影","Shadow the Hedgehog",
        "索尼克06",
        "索尼克失落世界",
        "索尼克力量",
        "索尼克起源","Sonic Origins",
        "索尼克超级明星",
        "索尼克未知边境",
        "噗哟噗哟","Puyo Puyo",
        "魔法气泡",
        "噗哟噗哟通",
        "噗哟噗哟2",
        "噗哟噗哟狂热",
        "噗哟噗哟7",
        "噗哟噗哟VS俄罗斯方块",
        "噗哟噗哟eSports",
        "魔法气泡eSports",
        "幻想空间","Fantasy Zone",
        "太空哈利","Space Harrier",
        "冲破火网","After Burner",
        "闪电出击","Thunder Blade",
        "超级忍","Super Shinobi",
        "忍Shinobi",
        "女忍Kunoichi",
        "街头涂鸦","Jet Set Radio","Jet Grind Radio",
        "疯狂出租车","Crazy Taxi",
        "太空第5频道","Space Channel 5",
        "莎木","Shenmue",
        "莎木一章横须贺",
        "莎木二",
        "莎木3",
        "如龙","Yakuza","Like a Dragon",
        "如龙0",
        "如龙极","Yakuza Kiwami",
        "如龙极2","Yakuza Kiwami 2",
        "如龙3",
        "如龙4",
        "如龙5",
        "如龙6",
        "如龙7","Yakuza Like a Dragon",
        "如龙8","Like a Dragon Infinite Wealth",
        "如龙见参",
        "如龙维新",
        "如龙维新极",
        "如龙北斗",
        "审判之眼","Judgment",
        "审判之逝","Lost Judgment",
        "黑豹如龙新章",
        "人中北斗",
        "VR战士","Virtua Fighter",
        "VF",
        "VF5终极版",
        "电脑战机","Virtual On",
        "Cyber Troopers",
        "铁甲飞龙","Panzer Dragoon",
        "飞龙RPG",
        "铁甲飞龙Zwei",
        "铁甲飞龙RPG",
        "铁甲飞龙Orta",
        "光明与黑暗","Shining and Darkness",
        "光明力量","Shining Force",
        "光明力量众神遗产",
        "光明力量古之封印",
        "光明力量三部曲",
        "光明之魂","Shining Soul",
        "光明之魂2",
        "光明之泪","Shining Tears",
        "光明之风","Shining Wind",
        "光明之心","Shining Hearts",
        "光明之刃","Shining Blade",
        "光明之舟","Shining Ark",
        "光明之响","Shining Resonance",
        "光明格斗",
        "Blade Arcus",
        "梦幻之星","Phantasy Star",
        "梦幻之星2",
        "梦幻之星4",
        "梦幻之星Online","Phantasy Star Online",
        "梦幻之星Online2",
        "梦幻之星宇宙",
        "梦幻之星携带版",
        "梦幻之星伊多拉传说",
        "樱花大战","Sakura Wars",
        "樱大战",
        "樱花大战2",
        "樱花大战3",
        "樱花大战4",
        "樱花大战V",
        "新樱花大战","New Sakura Wars",
        "樱大战物语",
        "樱花大战历代",
        "魔界战记","Disgaea",
        "魔界战记2",
        "魔界战记3",
        "魔界战记4",
        "魔界战记5",
        "魔界战记6",
        "魔界战记7",
        "魔界战记D2",
        "灵武战记",
        "光之圣女",
        "绝对英雄改造计划",
        "鬼魂王国",
        "浊水",
        "普利尼","Prinny",
        "普利尼2",
        "日本一全明星",
        "召唤之夜","Summon Night",
        "召唤之夜铸剑物语",
        "召唤之夜X泪光宝石",
        "召唤之夜5",
        "召唤之夜6",
        "弧光之源","Luminous Arc",
        "弧光之源2",
        "弧光之源3",
        "托尼",
        "元素少女",
        "Gust",
        "暗耻",
        "Blizzard",
        "动视","Activision",
        "动视暴雪",
        "King",
        "ZeniMax",
        "Bethesda",
        "贝塞斯达",
        "B社",
        "BioWare",
        "黑曜石","Obsidian",
        "黑曜石娱乐",
        "inXile",
        "Bungie",
        "棒鸡",
        "343 Industries",
        "The Coalition",
        "Turn 10",
        "Playground Games",
        "游乐场游戏",
        "Rare",
        "忍者理论","Ninja Theory",
        "黑马",
        "Complusive",
        "MachineGames",
        "id Software",
        "id社",
        "id Tech",
        "约翰卡马克",
        "毁灭战士","Doom",
        "DOOM",
        "DOOM 64",
        "DOOM 3",
        "DOOM 2016",
        "DOOM Eternal",
        "毁灭战士永恒",
        "雷神之锤","Quake",
        "Quake",
        "Quake 2",
        "Quake 3",
        "Quake 4",
        "Quake Champions",
        "Quake Live",
        "重返德军总部","Return to Castle Wolfenstein",
        "Wolfenstein",
        "德军总部",
        "德军总部新秩序",
        "德军总部旧血脉",
        "德军总部新巨人",
        "德军总部新血脉",
        "德军总部3D",
        "Wolfenstein 3D",
        "狂怒","Rage",
        "Rage 2",
        "狂怒2",
        "耻辱","Dishonored",
        "羞辱",
        "Dishonored 2",
        "Dishonored Death of the Outsider",
        "耻辱2",
        "耻辱界外魔之死",
        "掠食","Prey",
        "Prey 2017",
        "死亡循环","Deathloop",
        "幽灵线东京","Ghostwire Tokyo",
        "Hi-Fi Rush",
        "完美音浪",
        "上古卷轴","The Elder Scrolls",
        "TES",
        "上古卷轴竞技场","Arena",
        "上古卷轴匕首雨","Daggerfall",
        "上古卷轴晨风","Morrowind",
        "上古卷轴湮灭","Oblivion",
        "上古卷轴天际","Skyrim",
        "上古卷轴5",
        "上古卷轴Online","ESO",
        "辐射","Fallout",
        "Fallout 1",
        "Fallout 2",
        "Fallout 3",
        "Fallout New Vegas",
        "Fallout 4",
        "Fallout 76",
        "辐射战略版",
        "星空","Starfield",
        "恶灵附身","The Evil Within",
        "恶灵附身2",
        "Tango Gameworks",
        "征服",
        "幽灵",
        "三上真司",
        "神之浩劫","SMITE",
        "神之浩劫手游",
        "枪火游侠","Paladins",
        "枪火游侠冠军",
        "Realm Royale",
        "英雄领域",
        "Global Agenda",
        "部落",
        "Hi-Rez",
        "Valve",
        "V社",
        "拳头","Riot",
        "Riot Games",
        "Epic","Epic Games",
        "Epic Games Store",
        "虚幻引擎","Unreal Engine",
        "虚幻","Unreal",
        "虚幻竞技场","Unreal Tournament",
        "UT",
        "UT2004",
        "UT3",
        "战争机器","Gears of War",
        "战争机器2",
        "战争机器3",
        "战争机器4",
        "战争机器5",
        "战争机器战术小队",
        "子弹风暴","Bulletstorm",
        "ChAIR",
        "无尽之剑","Infinity Blade",
        "暗影无敌",
        "企鹅俱乐部","Club Penguin",
        "堡垒之夜","Fortnite",
        "Fortnite Save the World",
        "Fortnite Battle Royale",
        "堡垒之夜大逃杀",
        "火箭联盟","Rocket League",
        "Psyonix",
        "糖豆人","Fall Guys",
        "Mediatonic",
        "在我们之中","Among Us",
        "Innersloth",
        "泰拉瑞亚","Terraria",
        "Re-Logic",
        "星露谷物语","Stardew Valley",
        "ConcernedApe",
        "Eric Barone",
        "Mojang",
        "Minecraft",
        "Notch",
        "Markus Persson",
        "我的世界地下城","Minecraft Dungeons",
        "我的世界传奇","Minecraft Legends",
        "我的世界教育版",
        "我的地球",
        "粘粘世界","World of Goo",
        "蜡笔物理学",
        "地狱边境","Limbo",
        "Inside",
        "Playdead",
        "纪念碑谷","Monument Valley",
        "阿尔托的冒险","Alto Adventure",
        "阿尔托的奥德赛","Alto Odyssey",
        "风之旅人","Journey",
        "Thatgamecompany",
        "Flower",
        "花",
        "Flow",
        "浮游",
        "光之子","Child of Light",
        "勇敢的心","Valiant Hearts",
        "勇敢的心世界大战",
        "勇敢的心归乡",
        " soldats inconnus",
        "刺客信条编年史",
        "刺客信条2",
        "刺客信条兄弟会",
        "刺客信条启示录",
        "刺客信条3",
        "刺客信条4黑旗",
        "刺客信条大革命",
        "刺客信条枭雄",
        "刺客信条起源",
        "刺客信条奥德赛",
        "刺客信条英灵殿",
        "刺客信条幻景",
        "刺客信条影",
        "孤岛惊魂","Far Cry",
        "孤岛惊魂2",
        "孤岛惊魂3",
        "孤岛惊魂4",
        "孤岛惊魂5",
        "孤岛惊魂6",
        "孤岛惊魂原始杀戮",
        "孤岛惊魂血龙",
        "孤岛惊魂新曙光",
        "看门狗","Watch Dogs",
        "看门狗2",
        "看门狗军团",
        "细胞分裂","Splinter Cell",
        "细胞分裂断罪",
        "细胞分裂黑名单",
        "细胞分裂双面间谍",
        "细胞分裂混沌理论",
        "全境封锁","The Division",
        "全境封锁2",
        "彩虹六号","Rainbow Six",
        "彩虹六号围攻",
        "彩虹六号爱国者",
        "彩虹六号维加斯",
        "彩虹六号异种",
        "幽灵行动","Ghost Recon",
        "幽灵行动荒野",
        "幽灵行动断点",
        "幽灵行动未来战士",
        "幽灵行动尖峰战士",
        "舞力全开","Just Dance",
        "舞力全开2023",
        "舞力全开2024",
        "舞力全开2025",
        "荣耀战魂","For Honor",
        "飙酷车神","The Crew",
        "飙酷车神2",
        "飙酷车神轰鸣盛典",
        "纪元1800","Anno 1800",
        "纪元1404",
        "纪元2070",
        "纪元2205",
        "纪元1800",
        "纪元变异",
        "渡神纪","Immortals Fenyx Rising",
        "芬尼克斯传说",
        "南方公园真理之杖",
        "南方公园完整破碎",
        "特技摩托","Trials",
        "特技摩托进化",
        "特技摩托融合",
        "特技摩托崛起",
        "赛道狂飙","Trackmania",
        "赛道狂飙国家",
        "赛道狂飙2",
        "赛道狂飙2020",
        "极限巅峰","Steep",
        "Riders Republic",
        "极限国度",
        "阿凡达","Avatar",
        "阿凡达潘多拉边境",
        "星球大战",
        "星球大战旧共和国武士",
        "星球大战侠盗中队",
        "星球大战前线",
        "星球大战前线2",
        "星球大战战机中队",
        "星球大战绝地陨落的武士团",
        "星球大战绝地幸存者",
        "星球大战法外之徒",
        "星球大战银河英雄",
        "星球大战帝国战争",
        "星球大战旧共和国",
        "星球大战星系",
        "疯狂兔子","Rabbids",
        "疯狂兔子回家",
        "疯狂兔子大冒险",
        "马里奥疯狂兔子王国之战",
        "马里奥疯狂兔子希望之光",
        "雷曼","Rayman",
        "雷曼起源",
        "雷曼传奇",
        "雷曼2",
        "雷曼3",
        "雷曼疯狂兔子",
        "波斯王子","Prince of Persia",
        "波斯王子时之砂",
        "波斯王子武者之心",
        "波斯王子王者无双",
        "波斯王子遗忘之沙",
        "波斯王子2008",
        "波斯王子堕落",
        "波斯王子失落的王冠",
        "波斯王子Rogue",
        "细胞分裂","Splinter Cell",
        "超越善恶","Beyond Good and Evil",
        "布莱克与莫蒂",
        "黑暗之眼",
        "机械迷城","Machinarium",
        "银河历险记","Samorost",
        "植物精灵","Botanicula",
        "快乐游戏",
        "Amanita Design",
        "小小炼狱","Little Inferno",
        "人力资源机器","Human Resource Machine",
        "7 Billion Humans",
        "70亿人",
        "编程游戏",
        "Tomorrow Corporation",
        "World of Goo",
        "粘粘世界",
        "2D Boy",
        "时空幻境","Braid",
        "乔纳森布洛",
        "Jonathan Blow",
        "见证者","The Witness",
        "Feza",
        "Fez",
        "鱼",
        "超级肉食男孩","Super Meat Boy",
        "永远的好肉",
        "以撒的结合","Binding of Isaac",
        "重生",
        "Repentance",
        "悔改",
        "Edmund McMillen",
        "Team Meat",
        "杀戮尖塔","Slay the Spire",
        "Mega Crit",
        "陷阵之志","Into the Breach",
        "FTL超越光速","FTL Faster Than Light",
        "Subset Games",
        "暗黑地牢","Darkest Dungeon",
        "Red Hook",
        "红钩",
        "潜渊症","Barotrauma",
        "Brotato",
        "土豆兄弟",
        "吸血鬼幸存者","Vampire Survivors",
        "poncle",
        "杀戮小队","Boneraiser Minions",
        "灵魂石幸存者","Soulstone Survivors",
        "20 Minutes Till Dawn",
        "黎明前20分钟",
        "Magic Survival",
        "魔法生存",
        "Holocure",
        "Nomad Survivor",
        "流浪幸存者",
        "女巫幸存",
        "骨牌",
        "背包英雄","Backpack Hero",
        "背包乱斗","Backpack Battles",
        "背包战争",
        "循环英雄","Loop Hero",
        "Devolver Digital",
        "Devolver",
        "割草模拟",
        "模拟山羊","Goat Simulator",
        "Coffee Stain",
        "幸福工厂","Satisfactory",
        "看火人","Firewatch",
        "Campo Santo",
        "In the Valley of Gods",
        "众神之谷",
        "肯塔基零号公路","Kentucky Route Zero",
        "Cardboard Computer",
        "塔科马","Tacoma",
        "Fullbright",
        "回家","Gone Home",
        "艾迪芬奇的记忆","What Remains of Edith Finch",
        "Giant Sparrow",
        "亲爱的艾斯特","Dear Esther",
        "The Chinese Room",
        "失忆症","Amnesia The Dark Descent",
        "Frictional Games",
        "SOMA",
        "活体脑细胞",
        "半影","Penumbra",
        "黑山","Black Mesa",
        "Crowbar Collective",
        "异形隔离","Alien Isolation",
        "Creative Assembly",
        "全面战争","Total War",
        "Total War Rome",
        "Total War Rome 2",
        "Total War Medieval 2",
        "Total War Empire",
        "Total War Napoleon",
        "Total War Shogun 2",
        "Total War Attila",
        "Total War Warhammer",
        "Total War Warhammer 2",
        "Total War Warhammer 3",
        "Total War Three Kingdoms",
        "Total War Troy",
        "Total War Pharaoh",
        "坦克大战",
        "科乐美","Konami",
        "小岛秀夫","Hideo Kojima",
        "Kojima Productions",
        "小岛制作",
        "合金装备","Metal Gear Solid",
        "METAL GEAR",
        "燃烧战车",
        "合金装备索利德",
        "MGS1",
        "MGS2自由之子",
        "MGS3食蛇者",
        "MGS4爱国者之枪",
        "MGS5原爆点",
        "MGS5幻痛",
        "合金装备崛起复仇",
        "Metal Gear Rising Revengeance",
        "合金装备和平行者",
        "合金装备掌上行动",
        "合金装备Acid",
        "合金装备Ghost Babel",
        "合金装备双蛇",
        "寂静岭","Silent Hill",
        "Silent Hill 2",
        "Silent Hill 3",
        "寂静岭暴雨",
        "寂静岭归乡",
        "寂静岭起源",
        "寂静岭破碎的记忆",
        "寂静岭PT",
        "寂静岭短信",
        "恶魔城","Castlevania",
        "Castlevania Symphony of the Night",
        "月下夜想曲",
        "恶魔城被夺走的刻印",
        "恶魔城绝望的和声",
        "恶魔城月轮",
        "恶魔城白夜协奏曲",
        "恶魔城晓月圆舞曲",
        "恶魔城废墟的肖像",
        "恶魔城苍月的十字架",
        "恶魔城迷宫的画廊",
        "恶魔城血之轮回",
        "恶魔城XX",
        "恶魔城年表",
        "恶魔城暗影之王",
        "恶魔城暗影之王2",
        "魂斗罗","Contra",
        "魂斗罗1",
        "魂斗罗2超级魂斗罗",
        "魂斗罗3外星人战争",
        "魂斗罗4铁血兵团",
        "魂斗罗精神",
        "真魂斗罗",
        "新魂斗罗",
        "魂斗罗进化革命",
        "魂斗罗军团",
        "魂斗罗归来",
        "Konami",
        "科乐美",
        "桃太郎电铁",
        "桃铁",
        "实况棒球","Powerful Pro Baseball",
        "实况力量棒球",
        "eBaseball",
        "职棒魂",
        "职业棒球之魂",
        "J联盟胜利十一人",
        "游戏王","Yu-Gi-Oh",
        "Yu-Gi-Oh Duel Monsters",
        "游戏王决斗怪兽",
        "游戏王决斗链接",
        "Yu-Gi-Oh Duel Links",
        "游戏王大师决斗","Master Duel",
        "游戏王Cross Duel",
        "游戏王Rush Duel",
        "游戏王卡片力量",
        "游戏王世界冠军",
        "游戏王朝日版",
        "游戏王真DM",
        "游戏王GX",
        "游戏王5Ds",
        "游戏王ZEXAL",
        "游戏王ARC-V",
        "游戏王VRAINS",
        "DDR","Dance Dance Revolution",
        "热舞革命",
        "跳舞机",
        "Beatmania",
        "IIDX",
        "Pop Music",
        "大钢琴",
        "Guitar Freaks",
        "Drum Mania",
        "GFDM",
        "Jubeat",
        "Reflec Beat",
        "Sound Voltex",
        "SDVX",
        "噗哟噗哟",
        "GITADORA",
        "Nostalgia",
        "钢琴",
        "Dance Rush",
        "Bemani",
        "太鼓达人",
        "maimai",
        "舞萌",
        "中二节奏","CHUNITHM",
        "SEGA音游",
        "Cytus",
        "Deemo",
        "VOEZ",
        "Arcaea",
        "Phigros",
        "Muse Dash",
        "Lanota",
        "Dynamix",
        "Chain Bee",
        "Hexa Hive",
        "Orzmic",
        "韵律原典",
        "Rotaeno",
        "旋转音律",
        "KALPA",
        "VOEZ",
        "Tone Sphere",
        "同步音律",
        "Muse Dash",
        "喵斯",
        "BanG Dream",
        "D4DJ",
        "世界计划","Project Sekai",
        "初音未来","Hatsune Miku",
        "Miku",
        "初音",
        "镜音铃",
        "镜音连",
        "巡音流歌",
        "MEIKO",
        "KAITO",
        "VOCALOID",
        "歌姬计划","Project DIVA",
        "Project DIVA Arcade",
        "Project DIVA F",
        "Project DIVA F2",
        "Project DIVA X",
        "Project DIVA Mega 39s",
        "Project DIVA Future Tone",
        "Project DIVA Dreamy Theater",
        "Project Mirai",
        "未来计划",
        "KAITO物语",
        "Vocaloid",
        "CeVIO",
        "IA",
        "结月缘",
        "东北切蒲英",
        "樱花",
        "可不",
        "星界",
        "Neru",
        "P主",
        "PSYCHO-PASS",
        "心理测量者",
        "PP",
        "心理测量者游戏",
        "攻壳机动队","Ghost in the Shell",
        "攻壳机动队游戏",
        "壳中少女",
        "苹果核战记",
        "苹果核",
        "阿基拉","Akira",
        "AKIRA游戏",
        "星际牛仔","Cowboy Bebop",
        "星际牛仔游戏",
        "CB",
        "混沌武士","Samurai Champloo",
        "混沌武士游戏",
        "虫师",
        "虫师游戏",
        "夏目友人帐",
        "夏目",
        "萤火之森",
        "千与千寻","Spirited Away",
        "千与千寻游戏",
        "宫崎骏","Hayao Miyazaki",
        "吉卜力","Studio Ghibli",
        "吉卜力游戏",
        "二之国","Ni no Kuni",
        "二之国白色圣灰女王",
        "二之国亡灵之国",
        "二之国交错世界",
        "Level-5",
        "雷顿教授",
        "妖怪手表","Yo-kai Watch",
        "妖怪手表游戏",
        "闪电十一人","Inazuma Eleven",
        "闪电十一人GO",
        "闪电十一人英雄",
        "闪电十一人阿瑞斯",
        "纸箱战机","Little Battlers Experience",
        "纸箱战机W",
        "纸箱战机BOOST",
        "第二国度",
        "时空之轮",
        "幻想水浒传",
        "百英雄传","Eiyuden Chronicle",
        "百英雄传崛起",
        "百英雄传百年",
        "兽人必须","Orcs Must Die",
        "兽人必须死",
        "Robot Entertainment",
        "王国保卫战","Kingdom Rush",
        "Ironhide",
        "保卫萝卜",
        "Carrot Fantasy",
        "植物大战僵尸",
        "宝开","PopCap",
        "PopCap Games",
        "宝石迷阵","Bejeweled",
        "祖玛","Zuma",
        "祖玛的复仇",
        "吞食鱼","Feeding Frenzy",
        "毛毛","Chuzzle",
        "怪怪水族馆","Insaniquarium",
        "幻幻球","Peggle",
        "幻幻球之夜",
        "Peggle 2",
        "书虫","Bookworm",
        "三消",
        "俄罗斯方块",
        "Tetris",
        "Tetris Effect",
        "Tetris 99",
        "噗哟噗哟俄罗斯方块",
        "魔法气泡俄罗斯方块",
        "泡泡卡丁车",
        "疯狂坦克",
        "坦克宝贝",
        "弹弹堂",
        "弹弹堂S",
        "弹弹岛",
        "百战天虫","Worms",
        "Worms Armageddon",
        "Worms World Party",
        "虫子",
        "Team17",
        "百战天虫大混战",
        "百战天虫WMD",
        "轩辕剑","轩辕剑",
        "轩辕剑叁",
        "轩辕剑叁外传天之痕",
        "轩辕剑肆黑龙舞兮云飞扬",
        "轩辕剑肆外传苍之涛",
        "轩辕剑伍一剑凌云山海情",
        "轩辕剑伍外传云之遥",
        "轩辕剑陆凤凌长空千载云",
        "轩辕剑陆外传穹之扉",
        "轩辕剑柒",
        "轩辕剑网络版",
        "轩辕剑Online",
        "轩辕剑伏魔录",
        "轩辕剑轩辕伏魔录",
        "仙剑奇侠传",
        "仙剑奇侠传DOS",
        "仙剑奇侠传98柔情篇",
        "仙剑奇侠传2",
        "仙剑奇侠传3",
        "仙剑奇侠传3外传问情篇",
        "仙剑奇侠传4",
        "仙剑奇侠传5",
        "仙剑奇侠传5前传",
        "仙剑奇侠传6",
        "仙剑奇侠传7",
        "仙剑网络版",
        "仙剑Online",
        "仙剑客栈",
        "仙剑奇侠传手游",
        "大富翁",
        "大富翁1",
        "大富翁2",
        "大富翁3",
        "大富翁4",
        "大富翁6",
        "大富翁7",
        "大富翁8",
        "大富翁9",
        "大富翁10",
        "大富翁Online",
        "大富翁世界",
        "大富翁4fun",
        "大富翁梦",
        "明星志愿",
        "明星志愿2",
        "明星志愿2000",
        "明星志愿3",
        "明星志愿3甜蜜乐章",
        "明星志愿闯关",
        "明星志愿星之守护",
        "明星志愿手游",
        "美少女梦工厂","Princess Maker",
        "美少女梦工厂2",
        "美少女梦工厂3",
        "美少女梦工厂4",
        "美少女梦工厂5",
        "美少女梦工厂GO",
        "兰岛物语",
        "兰岛物语少女",
        "秋之回忆","Memories Off",
        "秋之回忆2",
        "秋之回忆3想君",
        "秋之回忆4从今以后",
        "秋之回忆5中断的胶片",
        "秋之回忆6三角波动",
        "秋之回忆7打勾勾的记忆",
        "秋之回忆8无垢少女",
        "告别回忆",
        "告别回忆历代",
        "Ever17",
        "Never7",
        "Remember11",
        "12RIVEN",
        "I/O",
        "时间轮回",
        "KID",
        "KID会社",
        "传颂之物","Utawarerumono",
        "传颂之物游戏",
        "传颂之物致逝者的摇篮曲",
        "传颂之物虚伪的假面",
        "传颂之物二人的白皇",
        "传颂之物斩",
        "迷宫旅人",
        "To Heart",
        "To Heart2",
        "暗夜魔法使",
        "夜明前的琉璃色",
        "夜明前的琉璃色",
        "黄昏的禁忌之药",
        "天神乱漫",
        "纯白交响曲",
        "纯白",
        "DRACU RIOT",
        "柚子社","Yuzusoft",
        "柚子",
        "千恋万花",
        "魔女的夜宴",
        "咖啡馆",
        "Riddle Joker",
        "星光咖啡馆与死神之蝶",
        "天使骚骚",
        "天使纷扰",
        "柚子社全明星",
        "苍之彼方的四重奏",
        "苍彼",
        "银魂",
        "银魂游戏",
        "Gintama",
        "美少年侦探团",
        "物语系列",
        "化物语",
        "伪物语",
        "伤物语",
        "猫物语",
        "花物语",
        "囮物语",
        "鬼物语",
        "恋物语",
        "凭物语",
        "终物语",
        "续终物语",
        "历物语",
        "抚物语",
        "业物语",
        "夏物语",
        "物语游戏",
        "魔法少女小圆","Madoka Magica",
        "小圆",
        "小圆游戏",
        "魔法少女",
        "魔圆",
        "魔法纪录","Magia Record",
        "魔法记录",
        "魔法少女小圆外传",
        "叛逆的物语",
        "向阳素描",
        "水星领航员",
        "ARIA",
        "轻音少女","K-ON",
        "轻音",
        "天使的3P",
        "萝球社",
        "萝球",
        "天才麻将少女","Saki",
        "咲",
        "咲-Saki",
        "阿知贺",
        "怜",
        "全国篇",
        "闪乱神乐","Senran Kagura",
        "闪乱神乐游戏",
        "弹闪乱",
        "忍乳负重",
        "死或生沙滩排球",
        "死或生沙滩排球3",
        "死或生沙滩排球维纳斯",
        "DOAXVV",
        "死或生6",
        "死或生5",
        "沙滩排球",
        "奶排",
        "维纳斯",
        "生死格斗",
        "真三国无双","Dynasty Warriors",
        "真三国无双2",
        "真三国无双3",
        "真三国无双4",
        "真三国无双5",
        "真三国无双6",
        "真三国无双7",
        "真三国无双8",
        "真三国无双起源",
        "战国无双","Samurai Warriors",
        "战国无双2",
        "战国无双3",
        "战国无双4",
        "战国无双5",
        "无双大蛇","Warriors Orochi",
        "无双大蛇2",
        "无双大蛇3",
        "无双大蛇Z",
        "无双大蛇魔王再临",
        "无双全明星",
        "无双群星",
        "塞尔达无双灾厄启示录",
        "Hyrule Warriors AoC",
        "火纹无双",
        "Fire Emblem Warriors",
        "Fire Emblem Warriors Three Hopes",
        "火纹无双风花雪月",
        "海贼无双",
        "One Piece Pirate Warriors",
        "海贼无双4",
        "剑刃风暴百年战争",
        "剑刃风暴噩梦",
        "忍者龙剑传","Ninja Gaiden",
        "忍者龙剑传Black",
        "忍者龙剑传2",
        "忍者龙剑传3",
        "忍者龙剑传刀锋边缘",
        "忍龙∑",
        "忍龙∑2",
        "忍者外传",
        "死或生",
        "仁王","Nioh",
        "仁王2",
        "卧龙苍天陨落","Wo Long Fallen Dynasty",
        "浪人崛起","Rise of the Ronin",
        "战国BASARA","Sengoku Basara",
        "婆娑罗",
        "Basara",
        "战国BASARA2",
        "战国BASARA3",
        "战国BASARA4",
        "战国BASARA真田幸村传",
        "战国BASARA战斗英雄",
        "怪物猎人物语","Monster Hunter Stories",
        "怪物猎人物语2",
        "怪猎物语2破灭之翼",
        "怪物猎人边境",
        "怪物猎人Online",
        "怪物猎人Now",
        "怪物猎人大狩猎",
        "怪物猎人探险",
        "怪物猎人独孤",
        "MH",
        "MHR",
        "MHW",
        "MHGU",
        "MHXX",
        "MHX",
        "MH4",
        "MH4G",
        "MH3",
        "MH3G",
        "MH3tri",
        "MHP3",
        "MHP2G",
        "MHP2",
        "MHP",
        "MH1",
        "MHG",
        "物语2",
        "艾露猫",
        "猫车",
        "火龙",
        "泡狐龙",
        "灭尽龙",
        "冰咒龙",
        "煌黑龙",
        "黑龙",
        "雷狼龙",
        "金狮子",
        "激昂金狮子",
        "天地煌啼龙",
        "冥赤龙",
        "霜刃冰牙龙",
        "冰牙龙",
        "轰龙",
        "迅龙",
        "斩龙",
        "碎龙",
        "黑蚀龙",
        "天廻龙",
        "爵银龙",
        "岚龙",
        "天彗龙",
        "骸龙",
        "蛇王龙",
        "大轰龙",
        "角龙",
        "黑角龙",
        "麒麟",
        "炎王龙",
        "炎妃龙",
        "钢龙",
        "霞龙",
        "尸套龙",
        "雾瘴尸套龙",
        "溟波龙",
        "天地龙",
        "狱狼龙",
        "猛牛龙",
        "痹毒龙",
        "雌火龙",
        "雄火龙",
        "樱火龙",
        "苍火龙",
        "银火龙",
        "金火龙",
        "日轮",
        "月辰",
        "星辰",
        "集会所",
        "猫饭",
        "龙击枪",
        "大剑",
        "太刀",
        "片手剑",
        "双剑",
        "大锤",
        "狩猎笛",
        "长枪",
        "铳枪",
        "斩斧",
        "充能斧",
        "盾斧",
        "操虫棍",
        "轻弩",
        "重弩",
        "弓箭",
        "弓",
    };

    private static readonly HashSet<string> _knownGameStudios = new(StringComparer.OrdinalIgnoreCase)
    {
        "米哈游","miHoYo",
        "腾讯","Tencent",
        "网易","NetEase",
        "任天堂","Nintendo",
        "索尼","Sony","PlayStation",
        "微软","Microsoft","Xbox",
        "育碧","Ubisoft",
        "EA","Electronic Arts",
        "卡普空","Capcom",
        "万代","Bandai Namco","Bandai",
        "世嘉","Sega",
        "科乐美","Konami",
        "史克威尔","Square Enix","Square",
        "暴雪","Blizzard",
        "Valve","V社",
        "拳头","Riot","Riot Games",
        "Epic","Epic Games",
        "Rockstar","R星",
        "CD Projekt","CDPR",
        "小岛制作","Kojima Productions",
        "顽皮狗","Naughty Dog",
        "圣莫尼卡","Santa Monica Studio",
        "B社","Bethesda",
        "BioWare",
        "生软",
        "动视","Activision",
        "光荣","KOEI","光荣特库摩",
        "Arc System Works",
        "法老控","Falcom",
        "日本一","Nippon Ichi",
        "Atlus","阿特拉斯",
        "FromSoftware",
        "白金工作室","PlatinumGames",
        "Gust","gust",
    };

    private static readonly HashSet<string> _knownGameDirectors = new(StringComparer.OrdinalIgnoreCase)
    {
        "宫崎英高","Hidetaka Miyazaki",
        "小岛秀夫","Hideo Kojima",
        "宫本茂","Shigeru Miyamoto",
        "席德梅尔","Sid Meier",
        "威尔莱特","Will Wright",
        "彼得莫利纽克斯","Peter Molyneux",
        "托德霍华德","Todd Howard",
        "岩田聪","Satoru Iwata",
        "樱井政博","Masahiro Sakurai",
        "三上真司","Shinji Mikami",
        "神谷英树","Hideki Kamiya",
        "五十岚孝司","Koji Igarashi","IGA",
        "铃木裕","Yu Suzuki",
        "约翰卡马克","John Carmack",
        "盖布纽维尔","Gabe Newell","GabeN",
        "艾米亨尼格","Amy Hennig",
        "肯莱文","Ken Levine",
        "提姆谢弗","Tim Schafer",
        "拉斐尔科兰托尼奥","Raphael Colantonio",
        "大卫贾菲","David Jaffe",
        "华伦斯塔普雷顿","Warren Spector",
        "克里斯罗伯茨","Chris Roberts",
        "理查德加里奥特","Richard Garriott",
        "布兰达罗梅罗","Brenda Romero",
        "约翰罗梅罗","John Romero",
        "卡马克","John Carmack",
        "杰森罗德里格斯","Jason Rohrer",
        "乔纳森布洛","Jonathan Blow",
        "埃德蒙麦克米伦","Edmund McMillen",
        "马库斯佩尔松","Markus Persson","Notch",
        "埃里克斯巴隆","Eric Barone","ConcernedApe",
        "陈星汉","Jenova Chen",
        "姚壮宪","姚仙",
        "张毅","张毅",
        "郭炜炜",
        "冯骥","冯骥",
    };

    public void TrackRejectedTask() { _rejectedTaskCount++; }
    public void TrackNameClash() { _hasNameClash = true; }
    public void TrackFiredCEO() { _hasFiredCEO = true; }

    public override void _Ready()
    {
        _gm = GetNode<GameManager>("..");
        if (GlobalSettings.NewGame)
            InitAchievements();
    }

    private void InitAchievements()
    {
        AllAchievements = new List<Achievement>
        {
            // ═══ 里程碑成就 ═══
            new() { Id = "first_game", Name = Loc.Tr("ach.first_game"), Desc = Loc.Tr("ach.first_game_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "first_hit", Name = Loc.Tr("ach.first_hit"), Desc = Loc.Tr("ach.first_hit_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "million_seller", Name = Loc.Tr("ach.million_seller"), Desc = Loc.Tr("ach.million_seller_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "ten_million", Name = Loc.Tr("ach.ten_million"), Desc = Loc.Tr("ach.ten_million_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "score_95", Name = Loc.Tr("ach.score_95"), Desc = Loc.Tr("ach.score_95_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "score_80", Name = Loc.Tr("ach.score_80"), Desc = Loc.Tr("ach.score_80_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "ten_games", Name = Loc.Tr("ach.ten_games"), Desc = Loc.Tr("ach.ten_games_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "fifty_games", Name = Loc.Tr("ach.fifty_games"), Desc = Loc.Tr("ach.fifty_games_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "year_10", Name = Loc.Tr("ach.year_10"), Desc = Loc.Tr("ach.year_10_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "year_30", Name = Loc.Tr("ach.year_30"), Desc = Loc.Tr("ach.year_30_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "money_100m", Name = Loc.Tr("ach.money_100m"), Desc = Loc.Tr("ach.money_100m_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "team_50", Name = Loc.Tr("ach.team_50"), Desc = Loc.Tr("ach.team_50_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "engine_v5", Name = Loc.Tr("ach.engine_v5"), Desc = Loc.Tr("ach.engine_v5_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "all_tech", Name = Loc.Tr("ach.all_tech"), Desc = Loc.Tr("ach.all_tech_desc"), Category = Loc.Tr("ach.cat_milestone") },
            new() { Id = "fan_1m", Name = Loc.Tr("ach.fan_1m"), Desc = Loc.Tr("ach.fan_1m_desc"), Category = Loc.Tr("ach.cat_milestone") },

            // ═══ 挑战成就 ═══
            new() { Id = "challenge_no_engine", Name = Loc.Tr("ach.challenge_no_engine"), Desc = Loc.Tr("ach.challenge_no_engine_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_solo", Name = Loc.Tr("ach.challenge_solo"), Desc = Loc.Tr("ach.challenge_solo_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_10in10", Name = Loc.Tr("ach.challenge_10in10"), Desc = Loc.Tr("ach.challenge_10in10_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_three_aaa", Name = Loc.Tr("ach.challenge_three_aaa"), Desc = Loc.Tr("ach.challenge_three_aaa_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_debt_zero", Name = Loc.Tr("ach.challenge_debt_zero"), Desc = Loc.Tr("ach.challenge_debt_zero_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_no_marketing", Name = Loc.Tr("ach.challenge_no_marketing"), Desc = Loc.Tr("ach.challenge_no_marketing_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_open_source", Name = Loc.Tr("ach.challenge_open_source"), Desc = Loc.Tr("ach.challenge_open_source_desc"), Category = Loc.Tr("ach.cat_challenge") },
            new() { Id = "challenge_all_genres", Name = Loc.Tr("ach.challenge_all_genres"), Desc = Loc.Tr("ach.challenge_all_genres_desc"), Category = Loc.Tr("ach.cat_challenge") },

            // ═══ 彩蛋成就 ═══
            new() { Id = "easter_trash", Name = Loc.Tr("ach.easter_trash"), Desc = Loc.Tr("ach.easter_trash_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_bankrupt", Name = Loc.Tr("ach.easter_bankrupt"), Desc = Loc.Tr("ach.easter_bankrupt_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_reject_100", Name = Loc.Tr("ach.easter_reject_100"), Desc = Loc.Tr("ach.easter_reject_100_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_name_clash", Name = Loc.Tr("ach.easter_name_clash"), Desc = Loc.Tr("ach.easter_name_clash_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_fired_ceo", Name = Loc.Tr("ach.easter_fired_ceo"), Desc = Loc.Tr("ach.easter_fired_ceo_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_cease_desist", Name = Loc.Tr("ach.easter_cease_desist"), Desc = Loc.Tr("ach.easter_cease_desist_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_man", Name = Loc.Tr("ach.easter_man"), Desc = Loc.Tr("ach.easter_man_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_bug_feature", Name = Loc.Tr("ach.easter_bug_feature"), Desc = Loc.Tr("ach.easter_bug_feature_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_free_game", Name = Loc.Tr("ach.easter_free_game"), Desc = Loc.Tr("ach.easter_free_game_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_trust_code", Name = Loc.Tr("ach.easter_trust_code"), Desc = Loc.Tr("ach.easter_trust_code_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_996", Name = Loc.Tr("ach.easter_996"), Desc = Loc.Tr("ach.easter_996_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_remaster_king", Name = Loc.Tr("ach.easter_remaster_king"), Desc = Loc.Tr("ach.easter_remaster_king_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_lucky7", Name = Loc.Tr("ach.easter_lucky7"), Desc = Loc.Tr("ach.easter_lucky7_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_company_name", Name = Loc.Tr("ach.easter_company_name"), Desc = Loc.Tr("ach.easter_company_name_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_founder_name", Name = Loc.Tr("ach.easter_founder_name"), Desc = Loc.Tr("ach.easter_founder_name_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_all_in", Name = Loc.Tr("ach.easter_all_in"), Desc = Loc.Tr("ach.easter_all_in_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_next_time", Name = Loc.Tr("ach.easter_next_time"), Desc = Loc.Tr("ach.easter_next_time_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_rival_hater", Name = Loc.Tr("ach.easter_rival_hater"), Desc = Loc.Tr("ach.easter_rival_hater_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_crocodile_tears", Name = Loc.Tr("ach.easter_crocodile_tears"), Desc = Loc.Tr("ach.easter_crocodile_tears_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_regardless", Name = Loc.Tr("ach.easter_regardless"), Desc = Loc.Tr("ach.easter_regardless_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_god_like", Name = Loc.Tr("ach.easter_god_like"), Desc = Loc.Tr("ach.easter_god_like_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_broken", Name = Loc.Tr("ach.easter_broken"), Desc = Loc.Tr("ach.easter_broken_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_lay_flat", Name = Loc.Tr("ach.easter_lay_flat"), Desc = Loc.Tr("ach.easter_lay_flat_desc"), Category = Loc.Tr("ach.cat_easter") },
            new() { Id = "easter_tanking", Name = Loc.Tr("ach.easter_tanking"), Desc = Loc.Tr("ach.easter_tanking_desc"), Category = Loc.Tr("ach.cat_easter") },
        };

        // 加载 Mod 自定义成就
        foreach (var dict in AchievementModDB.CustomAchievements)
        {
            if (dict.TryGetValue("id", out var idEl) && dict.TryGetValue("name", out var nameEl))
            {
                string desc = dict.TryGetValue("desc", out var descEl) ? descEl.GetString() ?? "" : "";
                string cat = dict.TryGetValue("category", out var catEl) ? catEl.GetString() ?? "" : "Mod";
                AllAchievements.Add(new Achievement
                {
                    Id = idEl.GetString(),
                    Name = nameEl.GetString(),
                    Desc = desc,
                    Category = cat,
                });
            }
        }
    }

    /// <summary>获取原始游戏（非后发内容）列表</summary>
    private List<GameProject> OriginalReleases(GameDevManager devMgr) =>
        devMgr.CompletedProjects.Where(p => p.PostRelease == PostReleaseType.None || p.BaseProject == null).ToList();

    /// <summary>游戏发售时立即检查评分/销量/数量相关成就</summary>
    public void OnGameReleased()
    {
        var devMgr = _gm.GetNodeOrNull<GameDevManager>("GameDevManager");
        var fanMgr = _gm.GetNodeOrNull<FanManager>("FanManager");
        var techMgr = _gm.GetNodeOrNull<TechManager>("TechManager");
        if (devMgr == null) return;

        NewUnlocks.Clear();

        var originals = OriginalReleases(devMgr);
        int releasedCount = originals.Count;
        int totalCompleted = devMgr.CompletedProjects.Count;
        float maxScore = devMgr.CompletedProjects.Max(p => p.FinalScore);
        float maxSales = devMgr.CompletedProjects.Max(p => p.Sales);

        TryUnlock("first_game", totalCompleted >= 1);
        TryUnlock("first_hit", maxScore >= 85);
        TryUnlock("million_seller", maxSales >= 1_000_000);
        TryUnlock("ten_million", maxSales >= 10_000_000);
        TryUnlock("score_95", maxScore >= 95);
        TryUnlock("score_80", maxScore >= 80);
        TryUnlock("ten_games", releasedCount >= 10);
        TryUnlock("fifty_games", releasedCount >= 50);

        // 挑战成就（游戏相关）
        var teamMgr = _gm.GetNodeOrNull<TeamManager>("TeamManager");
        var debtMgr = _gm.GetNodeOrNull<TechDebtManager>("TechDebtManager");
        TryUnlock("challenge_no_engine", devMgr.CompletedProjects.All(p => string.IsNullOrEmpty(p.EngineName) || p.EngineName == "无"));
        TryUnlock("challenge_solo", teamMgr != null && teamMgr.Teams.Count == 1 && releasedCount >= 3);
        TryUnlock("challenge_10in10", releasedCount >= 10 && _gm.GameYear <= 10);
        TryUnlock("challenge_three_aaa", teamMgr != null
            && teamMgr.Teams.Count(t => t.CurrentProject != null && t.CurrentProject.Scale > 0.7f) >= 3);
        TryUnlock("challenge_debt_zero", debtMgr != null && debtMgr.ComputeTotalDebt() == 0 && totalCompleted >= 1);
        TryUnlock("challenge_no_marketing", devMgr.CompletedProjects.Any(p =>
            p.Sales >= 1_000_000 && p.Marketing == MarketingStrategy.LowKey));
        TryUnlock("challenge_all_genres", releasedCount >= 6
            && originals.Select(p => p.Genre).Distinct().Count() >= 5);

        // 彩蛋
        TryUnlock("easter_trash", devMgr.CompletedProjects.Any(p => p.FinalScore < 30));
        TryUnlock("easter_cease_desist",
            totalCompleted > 0 && _knownBigGames.Contains(devMgr.CompletedProjects.Last().Name));
        TryUnlock("easter_man",
            totalCompleted > 0 && "复活牢大".Equals(devMgr.CompletedProjects.Last().Name, StringComparison.OrdinalIgnoreCase));
        TryUnlock("easter_bug_feature",
            devMgr.CompletedProjects.Any(p => p.BugCount > 50 && p.FinalScore >= 80));
        TryUnlock("easter_free_game",
            devMgr.CompletedProjects.Any(p => p.PriceModel == PriceModel.Free && p.Sales >= 500000));
        TryUnlock("easter_trust_code",
            totalCompleted > 0
            && string.IsNullOrEmpty(devMgr.CompletedProjects.Last().QATestReport)
            && devMgr.CompletedProjects.Last().FinalScore >= 80);
        TryUnlock("easter_remaster_king",
            devMgr.CompletedProjects.Count(p => p.PostRelease == PostReleaseType.Remaster) >= 5);
        TryUnlock("easter_lucky7",
            devMgr.CompletedProjects.Any(p => p.FinalScore >= 70 && p.OriginalReleaseMonth == 91));
        TryUnlock("easter_crocodile_tears",
            devMgr.CompletedProjects.Any(p => p.FinalScore < 30 && p.Sales >= 500000));
        TryUnlock("easter_regardless",
            devMgr.CompletedProjects.Any(p => p.FinalScore < 40 && p.Sales >= 1000000));
        TryUnlock("easter_god_like",
            devMgr.CompletedProjects.Any(p => p.MonthsOnMarket >= 18));
        TryUnlock("easter_tanking",
            originals.Count >= 3 && originals.OrderByDescending(p => p.OriginalReleaseMonth).Take(3).All(p => p.FinalScore < 40));

        // 科技相关
        TryUnlock("engine_v5", _gm.Engines.Any(e => e.Generation >= 5));
        TryUnlock("all_tech", techMgr != null && TechTreeData.AllTech.Count > 0
            && TechTreeData.AllTech.Keys.All(id => techMgr.ResearchedTech.ContainsKey(id) && techMgr.ResearchedTech[id]));
        TryUnlock("fan_1m", fanMgr != null && fanMgr.TotalFans >= 1_000_000);

        ShowNewUnlocks();
    }

    /// <summary>金钱变化时检查（每次收入/支出后）</summary>
    public void OnMoneyChanged(float currentMoney)
    {
        TryUnlock("money_100m", currentMoney >= 100_000_000);
    }

    /// <summary>员工数量变化时检查</summary>
    public void OnEmployeeChanged(int employeeCount)
    {
        TryUnlock("team_50", employeeCount >= 50);
    }

    /// <summary>年份变化时检查</summary>
    public void OnYearChanged(int year)
    {
        TryUnlock("year_10", year >= 10);
        TryUnlock("year_30", year >= 30);
    }

    private void ShowNewUnlocks()
    {
        foreach (var id in NewUnlocks)
        {
            var ach = AllAchievements.Find(a => a.Id == id);
            if (ach != null)
                _gm.ShowPopup(Loc.Tr("ach.unlock_title"), $"[{ach.Category}]\n{ach.Name}\n{ach.Desc}", new Color(0.9f, 0.7f, 0.1f));
        }
    }

    /// <summary>每月检查成就（仅检查非游戏发售触发的成就：时间、金钱、彩蛋）</summary>
    public void MonthlyCheck()
    {
        var res = _gm.GetNodeOrNull<ResourceManager>("ResourceManager");
        var empMgr = _gm.GetNodeOrNull<EmployeeManager>("EmployeeManager");
        var devMgr = _gm.GetNodeOrNull<GameDevManager>("GameDevManager");
        var techMgr = _gm.GetNodeOrNull<TechManager>("TechManager");
        if (res == null || devMgr == null) return;

        NewUnlocks.Clear();

        int totalCompleted = devMgr.CompletedProjects.Count;
        var originals = OriginalReleases(devMgr);
        int totalYears = _gm.GameYear;

        // 时间相关
        TryUnlock("year_10", totalYears >= 10);
        TryUnlock("year_30", totalYears >= 30);

        // 状态快照（每月兜底）
        TryUnlock("money_100m", res.Money >= 100_000_000);
        if (empMgr != null) TryUnlock("team_50", empMgr.Employees.Count >= 50);
        TryUnlock("engine_v5", _gm.Engines.Any(e => e.Generation >= 5));
        TryUnlock("all_tech", techMgr != null && TechTreeData.AllTech.Count > 0
            && TechTreeData.AllTech.Keys.All(id => techMgr.ResearchedTech.ContainsKey(id) && techMgr.ResearchedTech[id]));
        var fanMgr = _gm.GetNodeOrNull<FanManager>("FanManager");
        if (fanMgr != null) TryUnlock("fan_1m", fanMgr.TotalFans >= 1_000_000);

        // 挑战（长期积累型）
        TryUnlock("challenge_open_source",
            _gm.Engines.Any(e => e.BizModel == EngineBizModel.OpenSource && e.LicenseCount >= 100));

        // 彩蛋成就（月检）
        TryUnlock("easter_bankrupt", res.Money <= 0 && totalCompleted > 0);
        TryUnlock("easter_reject_100", _rejectedTaskCount >= 100);
        TryUnlock("easter_name_clash", _hasNameClash);
        TryUnlock("easter_fired_ceo", _hasFiredCEO);
        var debtMgr = _gm.GetNodeOrNull<TechDebtManager>("TechDebtManager");
        TryUnlock("easter_996", debtMgr != null && debtMgr.ActiveCrunchMonths >= 6);
        TryUnlock("easter_company_name", _gm.Founder != null && _knownGameStudios.Contains(_gm.Founder.CompanyName));
        TryUnlock("easter_founder_name", _gm.Founder != null && _knownGameDirectors.Contains(_gm.Founder.Name));
        TryUnlock("easter_all_in", devMgr.Projects.Count(p => !p.IsReleased && p.Phase == DevPhase.Developing) >= 3);
        TryUnlock("easter_next_time", devMgr.CompletedProjects.Any(p => p.DelayCount >= 3));
        TryUnlock("easter_rival_hater", _gm.CorpActions.ActionLogs.Count >= 10);
        if (empMgr != null)
            TryUnlock("easter_broken", empMgr.Employees.Count > 0 && empMgr.Employees.All(e => e.Satisfaction < 20));
        TryUnlock("easter_god_like", devMgr.CompletedProjects.Any(p => p.MonthsOnMarket >= 18));
        // 躺平计数器（仅当有未发布项目时才检查）
        if (devMgr.Projects.Any(p => !p.IsReleased))
        {
            if (devMgr.Projects.All(p => p.IsReleased || p.Phase != DevPhase.Developing)) _idleMonths++;
            else _idleMonths = 0;
        }
        TryUnlock("easter_lay_flat", _idleMonths >= 6);

        ShowNewUnlocks();
    }

    public void TryUnlock(string id, bool condition)
    {
        if (!Unlocked.Contains(id) && condition)
        {
            Unlocked.Add(id);
            NewUnlocks.Add(id);
        }
    }

    /// <summary>获取成就完成度</summary>
    public (int unlocked, int total) GetProgress()
    {
        return (Unlocked.Count, AllAchievements.Count);
    }
}

/// <summary>
/// 单个成就
/// </summary>
public class Achievement
{
    public string Id { get; set; }
    public string Name { get; set; }
    public string Desc { get; set; }
    public string Category { get; set; } // Loc.Tr("ach.cat_milestone") / Loc.Tr("ach.cat_challenge") / Loc.Tr("ach.cat_easter")
}
